### ISSUE TITLE
Bring back support for non go modules projects

### ISSUE THREAD

**Issue by Bobgy** [google/go-licenses#128]
In v1.1, we made a breaking change of no longer supporting non go modules managed projects per discussions in https://github.com/google/go-licenses/issues/70. However, https://github.com/google/go-licenses/issues/125 seems to show that some users are still using GOPATH.

Creating this issue to track users who are still using GOPATH mode.
Please thumbs up if this affected you or comment about your scenario.

**Comment by Bobgy** [comment]
JFYI, you can keep using go-licenses v1.0.0 before any further actions are taken.

```
go install github.com/google/go-licenses@v1.0.0
```

**Comment by TylerGillson** [comment]
@Bobgy this is impacting our GH actions using the following config:
```yaml
jobs:
  golicense-pr-scan:
    runs-on: ubuntu-latest
    steps:
      - name: install-git
        run: sudo apt-get install -y git

      - name: install-golicenses
        run: GOBIN=/usr/local/bin go install github.com/google/go-licenses@latest

      - name: checkout
        uses: actions/checkout@v3

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USER: ${{ secrets.USER }}
        run: git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Stage binaries
        run: make binaries

      - name: golicense-scan
        run: |
          go-licenses check ./... --ignore github.com/myorg
```

We can't downgrade to v1.0.0 as we require `--ignore`. Any suggestions?
